# -*- coding: utf-8 -*-
"""ML_Model_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hlR4VF5AZy9x_p6601oaBfznnWQ6NR5E
"""

# =========================
# STEP 0: Import Libraries
# =========================
import pandas as pd
import numpy as np

# =========================
# STEP 1: Load Dataset
# =========================
df = pd.read_csv("/content/drive/MyDrive/AI_hackathon/site_1_preprocessed.csv")

print("Initial Shape:", df.shape)
print("\nMissing Values:\n", df.isnull().sum())
columns_to_drop = [
    "NO2_satellite",
    "HCHO_satellite",
    "ratio_satellite"
]
if "year" in df.columns:
    df = df.drop(columns=["year"])


# =========================
# STEP 4: Remove Any Remaining Missing Rows
# =========================
df = df.dropna()

print("\nShape After Cleaning:", df.shape)


# =========================
# STEP 5: Select Only Relevant Columns
# =========================

required_columns = [
    "month", "day", "hour",
    "O3_forecast",
    "NO2_forecast",
    "T_forecast",
    "q_forecast",
    "u_forecast",
    "v_forecast",
    "w_forecast",
    "O3_target"
]

df = df[required_columns]


# =========================
# STEP 6: Remove Extreme Outliers (Optional but Safe)
# =========================
# Using IQR Method

def remove_outliers_iqr(data):
    Q1 = data.quantile(0.25)
    Q3 = data.quantile(0.75)
    IQR = Q3 - Q1
    return data[~((data < (Q1 - 1.5 * IQR)) | (data > (Q3 + 1.5 * IQR))).any(axis=1)]

df = remove_outliers_iqr(df)

print("\nShape After Outlier Removal:", df.shape)


# =========================
# STEP 7: Reset Index
# =========================
df.reset_index(drop=True, inplace=True)


# =========================
# STEP 8: Save Clean Dataset
# =========================
df.to_csv("site_1_cleaned.csv", index=False)

print("\nDataset cleaned and saved successfully!")
print("Final Shape:", df.shape)
df.head()

from google.colab import drive
drive.mount('/content/drive')

X = df.drop("O3_target", axis=1)
y = df["O3_target"]

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Assuming 'X' is your features and 'y' is your target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Define the MLP model
model = keras.Sequential([
    layers.Dense(128, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    layers.Dropout(0.2),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(1) # Output layer for regression
])

# Compile the model
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

model.summary()

# Train the model
history = model.fit(
    X_train_scaled, y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

import matplotlib.pyplot as plt

# Plot training history
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss Over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss (MSE)')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['mae'], label='Training MAE')
plt.plot(history.history['val_mae'], label='Validation MAE')
plt.title('Model MAE Over Epochs')
plt.xlabel('Epoch')
plt.ylabel('MAE')
plt.legend()

plt.tight_layout()
plt.show()

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Evaluate the model on the test set
loss, mae = model.evaluate(X_test_scaled, y_test, verbose=0)
print(f'Test Loss (MSE): {loss:.4f}')
print(f'Test MAE: {mae:.4f}')

# Make predictions
y_pred_dl = model.predict(X_test_scaled).flatten()

# Calculate additional metrics
mse_dl = mean_squared_error(y_test, y_pred_dl)
rmse_dl = np.sqrt(mse_dl)
r2_dl = r2_score(y_test, y_pred_dl)

print(f'Test RMSE: {rmse_dl:.4f}')
print(f'Test R2 Score: {r2_dl:.4f}')
performance = {}
# Store results for comparison
performance['Deep Learning'] = {
    "MAE": mae,
    "RMSE": rmse_dl,
    "R2 Score": r2_dl,
    "Accuracy (%)": r2_dl * 100
}

# Display updated performance DataFrame
performance_df = pd.DataFrame(performance).T
display(performance_df)

import matplotlib.pyplot as plt

# Plot actual vs predicted for Deep Learning
plt.figure(figsize=(10, 5))
plt.plot(y_test.values, label="Actual", linewidth=2)
plt.plot(y_pred_dl, label="Predicted (Deep Learning)", linestyle="--")
plt.title("Deep Learning: Actual vs Predicted O3")
plt.xlabel("Time Index")
plt.ylabel("O3 Concentration")
plt.legend()
plt.show()

"""### Association Rule Mining"""

from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder
import pandas as pd

# Make a copy to avoid modifying the original DataFrame
df_arm = df.copy()

# Discretize numerical features into categorical bins
# For demonstration, let's discretize O3_target, O3_forecast, and T_forecast

# O3_target discretization
df_arm['O3_target_level'] = pd.cut(
    df_arm['O3_target'],
    bins=[0, 30, 60, np.inf],
    labels=['O3_Low', 'O3_Medium', 'O3_High'],
    right=False
)

# O3_forecast discretization
df_arm['O3_forecast_level'] = pd.cut(
    df_arm['O3_forecast'],
    bins=[0, 30, 60, np.inf],
    labels=['O3_Fc_Low', 'O3_Fc_Medium', 'O3_Fc_High'],
    right=False
)

# T_forecast (Temperature) discretization
df_arm['T_forecast_level'] = pd.cut(
    df_arm['T_forecast'],
    bins=[-np.inf, 273.15 + 10, 273.15 + 20, 273.15 + 30, np.inf], # Example bins in Kelvin (approx. 10C, 20C, 30C)
    labels=['Temp_VeryCold', 'Temp_Cold', 'Temp_Moderate', 'Temp_Warm'],
    right=False
)

# Select the features for ARM (including original categorical and new discretized ones)
arm_features = ['month', 'day', 'hour', 'O3_target_level', 'O3_forecast_level', 'T_forecast_level']
df_arm_selected = df_arm[arm_features].astype(str)

# Prepare data for Apriori by one-hot encoding each transaction
# Each row represents a 'transaction' of conditions/levels
# We'll create a list of lists where each inner list contains the 'items' for that transaction

transactions = df_arm_selected.apply(lambda x: list(x.values), axis=1).tolist()

te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df_transactions = pd.DataFrame(te_ary, columns=te.columns_)

display(df_transactions.head())

# Find frequent itemsets using the Apriori algorithm
frequent_itemsets = apriori(df_transactions, min_support=0.05, use_colnames=True)

print("Frequent Itemsets:")
display(frequent_itemsets.head())

# Generate association rules
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)

print("\nAssociation Rules:")
display(rules.sort_values(by='lift', ascending=False).head())

"""### Interpretation of Association Rules:

*   **Support**: How frequently the itemset appears in the dataset. A support of 0.05 means the itemset occurs in 5% of the transactions.
*   **Confidence**: Indicates how often the rule is true. For `A => B`, it's the probability of `B` given `A` (P(B|A)). A confidence of 0.8 means that 80% of transactions containing `A` also contain `B`.
*   **Lift**: Measures how much more likely `B` is to occur given `A`, compared to `B` occurring independently. A lift greater than 1 indicates a positive correlation, less than 1 indicates a negative correlation, and 1 indicates no correlation. A higher lift value is generally better.
"""

df.to_csv("/content/drive/MyDrive/AI_hackathon/site_1_cleaned.csv", index=False)

X = df.drop("O3_target", axis=1)
y = df["O3_target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

models = {
    "Linear Regression": LinearRegression(),
    "KNN": KNeighborsRegressor(n_neighbors=5),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42)
}

results = {}

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

for name, model in models.items():

    # Use scaled data for KNN, original for others
    if name == "KNN":
        model.fit(X_train_scaled, y_train)
        predictions = model.predict(X_test_scaled)
    else:
        model.fit(X_train, y_train)
        predictions = model.predict(X_test)

    mae = mean_absolute_error(y_test, predictions)
    mse = mean_squared_error(y_test, predictions)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, predictions)

    results[name] = [mae, rmse, r2]

print("Training Complete")

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

performance = {}

for name, model in models.items():

    if name == "KNN":
        predictions = model.predict(X_test_scaled)
    else:
        predictions = model.predict(X_test)

    mae = mean_absolute_error(y_test, predictions)
    mse = mean_squared_error(y_test, predictions)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, predictions)
    accuracy_percent = r2 * 100

    performance[name] = {
        "MAE": mae,
        "RMSE": rmse,
        "R2 Score": r2,
        "Accuracy (%)": accuracy_percent
    }

performance_df = pd.DataFrame(performance).T
performance_df

results_df = pd.DataFrame(results,
                          index=["MAE", "RMSE", "R2 Score"]).T

results_df

import matplotlib.pyplot as plt

rf = models["Random Forest"]

rf.fit(X_train, y_train)
rf_predictions = rf.predict(X_test)

plt.figure(figsize=(10,5))
plt.plot(y_test.values, label="Actual")
plt.plot(rf_predictions, label="Predicted")
plt.legend()
plt.title("Random Forest: Actual vs Predicted O3")
plt.show()

import matplotlib.pyplot as plt
def plot_predictions(model, model_name, use_scaled=False):

    if use_scaled:
        predictions = model.predict(X_test_scaled)
    else:
        predictions = model.predict(X_test)

    plt.figure(figsize=(10,5))
    plt.plot(y_test.values, label="Actual", linewidth=2)
    plt.plot(predictions, label="Predicted", linestyle="--")
    plt.title(f"{model_name}: Actual vs Predicted O3")
    plt.xlabel("Time Index")
    plt.ylabel("O3 Concentration")
    plt.legend()
    plt.show()

lr = LinearRegression()
lr.fit(X_train, y_train)

plot_predictions(lr, "Linear Regression")

knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train_scaled, y_train)

plot_predictions(knn, "KNN", use_scaled=True)

dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train, y_train)

plot_predictions(dt, "Decision Tree")

import pandas as pd
from sklearn.preprocessing import StandardScaler

# Load cleaned dataset
df = pd.read_csv("/content/drive/MyDrive/AI_hackathon/site_1_cleaned.csv")

# Remove target (unsupervised learning)
X_cluster = df.drop("O3_target", axis=1)

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_cluster)

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

inertia = []

for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8,5))
plt.plot(range(1,11), inertia, marker='o')
plt.title("Elbow Method for Optimal K")
plt.xlabel("Number of Clusters")
plt.ylabel("Inertia")
plt.show()

kmeans = KMeans(n_clusters=3, random_state=42)
df["KMeans_Cluster"] = kmeans.fit_predict(X_scaled)

from scipy.cluster.hierarchy import dendrogram, linkage

linked = linkage(X_scaled, method='ward')

plt.figure(figsize=(10,5))
dendrogram(linked,
           truncate_mode='level',
           p=5)
plt.title("Hierarchical Clustering Dendrogram")
plt.show()

from sklearn.cluster import AgglomerativeClustering

hc = AgglomerativeClustering(n_clusters=3)
df["Hierarchical_Cluster"] = hc.fit_predict(X_scaled)

from sklearn.cluster import DBSCAN

dbscan = DBSCAN(eps=0.5, min_samples=5)
df["DBSCAN_Cluster"] = dbscan.fit_predict(X_scaled)

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

df["PCA1"] = X_pca[:, 0]
df["PCA2"] = X_pca[:, 1]

plt.figure(figsize=(8,6))
plt.scatter(df["PCA1"], df["PCA2"],
            c=df["KMeans_Cluster"], cmap='viridis')
plt.title("K-Means Clustering")
plt.xlabel("PCA1")
plt.ylabel("PCA2")
plt.colorbar()
plt.show()

plt.figure(figsize=(8,6))
plt.scatter(df["PCA1"], df["PCA2"],
            c=df["Hierarchical_Cluster"], cmap='plasma')
plt.title("Hierarchical Clustering")
plt.show()

plt.figure(figsize=(8,6))
plt.scatter(df["PCA1"], df["PCA2"],
            c=df["DBSCAN_Cluster"], cmap='coolwarm')
plt.title("DBSCAN Clustering")
plt.show()

from sklearn.metrics import silhouette_score

print("KMeans Silhouette Score:", silhouette_score(X_scaled, df["KMeans_Cluster"]))
print("Hierarchical Silhouette Score:", silhouette_score(X_scaled, df["Hierarchical_Cluster"]))

# Only compute DBSCAN score if it formed more than 1 cluster
if len(set(df["DBSCAN_Cluster"])) > 1:
    print("DBSCAN Silhouette Score:", silhouette_score(X_scaled, df["DBSCAN_Cluster"]))

# =========================
# MODEL COMPARISON SECTION
# =========================

import pandas as pd
import matplotlib.pyplot as plt

# Combine all performance results
# (You already stored ML models in 'performance')

# Add Deep Learning results
performance["Deep Learning"] = {
    "MAE": mae,                 # from DL evaluation
    "RMSE": rmse_dl,
    "R2 Score": r2_dl,
    "Accuracy (%)": r2_dl * 100
}

# Convert to DataFrame
comparison_df = pd.DataFrame(performance).T

# Sort by R2 Score (best model on top)
comparison_df = comparison_df.sort_values(by="R2 Score", ascending=False)

print("🔍 Model Comparison:")
display(comparison_df)

# =========================
# MODEL COMPARISON SECTION
# =========================

import pandas as pd
import matplotlib.pyplot as plt

# Combine all performance results
# (You already stored ML models in 'performance')

# Add Deep Learning results
performance["Deep Learning"] = {
    "MAE": mae,                 # from DL evaluation
    "RMSE": rmse_dl,
    "R2 Score": r2_dl,
    "Accuracy (%)": r2_dl * 100
}

# Convert to DataFrame
comparison_df = pd.DataFrame(performance).T

# Sort by R2 Score (best model on top)
comparison_df = comparison_df.sort_values(by="R2 Score", ascending=False)

print("🔍 Model Comparison:")
display(comparison_df)

# =========================
# VISUAL COMPARISON
# =========================

# Plot R2 Score comparison
plt.figure(figsize=(10,5))
comparison_df["R2 Score"].plot(kind='bar')
plt.title("Model Comparison - R2 Score")
plt.ylabel("R2 Score")
plt.xticks(rotation=45)
plt.show()


# Plot RMSE comparison
plt.figure(figsize=(10,5))
comparison_df["RMSE"].plot(kind='bar')
plt.title("Model Comparison - RMSE")
plt.ylabel("RMSE (Lower is Better)")
plt.xticks(rotation=45)
plt.show()


# Plot MAE comparison
plt.figure(figsize=(10,5))
comparison_df["MAE"].plot(kind='bar')
plt.title("Model Comparison - MAE")
plt.ylabel("MAE (Lower is Better)")
plt.xticks(rotation=45)
plt.show()